Instuctions: Type your code or solution in Colab. Upload the '.pdf' file onto Blackboard before Feb. 24 (18:15).

Name: Ng Wing Yin



SID: 1155127101

# Problem 1

 Implement the conjugate-gradient method on the following problem
 
 $$\min_{x,y,z}   x^2 + y^2 + 2z^2 - xy + yz -5x - 2y + 7z - 3$$

 (a) Rewrite the function as a quadratic form: 
$$ f(x,y,z)= \frac{1}{2}\left[\begin{array}{ccc} x &y &z \end{array}\right] Q \left[\begin{array}{c} x \\ y \\z  \end{array}\right]- {\bf b}^T \left[\begin{array}{c} x \\y \\z \end{array}\right] + c$$
Print the matrix $Q$, the vector ${\bf b}$ and the constant $c$.

In [1]:
# Answer:
import numpy as np

Q = np.array([[2, -1, 0], [-1, 2, 1], [0, 1, 4]])
b = np.array([5, 2, -7])
c = -3

print("Q:", Q)
print("b:", b)
print("c:", c)

Q: [[ 2 -1  0]
 [-1  2  1]
 [ 0  1  4]]
b: [ 5  2 -7]
c: -3


(b) Implement the conjugate-gradient method.

In [51]:
#Answer

t = np.array([0, 0, 0])
d = [b - Q @ t]
g = -b

for i in range(3):
  t = t + -(g.T @ d[i]) / (d[i].T @ Q @ d[i])
  g = Q @ t - b
  d.append(-g + ((g.T @ Q @ d[i]) / (d[i].T @ Q @ d[i])) * d[i])

(c) Print the result obtained in (b).

In [45]:
#Answer

print(t)

[0.45300288 0.45300288 0.45300288]


(d) Show that the conjugate directions are $Q$-orthogonal (where $Q$ is the matrix in the quadratic form).

In [60]:
#Answer
print(d[0].T @ Q @ d[1])

-1.7763568394002505e-14


# Problem 2


(a) Print out the hostname (id) of your virtual desktop

In [1]:
# Answer
!hostname

6d15d6201fc1


(b) Import the data set 'load_digits' from 'sklearn.datasets'. Check out the 'keys' of the data set.

In [10]:
# Answer
from sklearn.datasets import load_digits

dataset = load_digits()
print(dataset.keys())

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])


(c) Split the data set into training and test data sets. Find the size of the training data set and test data set.

In [12]:
# Answer
from sklearn.model_selection import train_test_split

X = dataset.data
Y = dataset.target
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
print("Size of the training data set:", len(X_train))
print("Size of the test data set:", len(X_test))

Size of the training data set: 1347
Size of the test data set: 450


(d) Using the Scikit-learn package, construct a classifier by applying the method of logistic regression.

In [39]:
# Answer
from sklearn.linear_model import LogisticRegression

lr2 = LogisticRegression(penalty='none')
lr2.fit(X_train, Y_train)

LogisticRegression(penalty='none')

(e) Compute the confusion matrices and the accuracy scores for the (i) training and (ii) test data, respectively.

In [76]:
# Answer
from sklearn.metrics import confusion_matrix

C_train = confusion_matrix(dataset.target[:len(Y_train)], Y_train)
C_test = confusion_matrix(dataset.target[:len(Y_test)], Y_test)

print(C_train)
print(C_test)

[[12 12 17 11 12 13 16 15  8 19]
 [12 16 11 20 10 11  7 20 15 14]
 [13 11 15 18 23  9 15  9 11 10]
 [15 16  7 13 24 11 16 13 10 11]
 [16  5 18 12 11 16 15 21 11  8]
 [14 10 10 10 18 13 20 13 12 17]
 [14 11 18 10 16 17 12 14  8 14]
 [16  9 11 12 15 13 13 12 17 16]
 [18 23 11 12  9 11 12 11  8 18]
 [ 3 15 17 13 11 18 14 11 23 10]]
[[ 5  4  4  7  4  4  2  4  6  7]
 [ 2  6  4  5  3  9  5  5  3  3]
 [ 4  7  2  5  6  2  3  5 11  1]
 [ 7  8  3  4  2  4  6  5  3  6]
 [ 4  5  3  7  4  4  4  4  5  2]
 [ 5  3  5  4  5  5  5  1  5  8]
 [ 1  6  7  6  1  5  3  4  5  5]
 [ 8  2  6  6  0  8  4  2  5  4]
 [ 3  5  5  4  5  2  4  6  6  4]
 [ 6  8  3  4  2  7  5  4  2  3]]
