# Question 1

a) (2%) Write down your name and student ID.

Name: Ng Wing Yin

Student ID: 1155127101

b) (2%) Print out the host id of the google colab session.

In [ ]:
!hostname

f10412f6c6e7


c) (2%) List two of the version-controlled repository providers that are free online.

Github and Bitbucket

d) (2%) Write down the function name of the BLAS 3 operation for real single precision general matrix vector multiplication.

sgemv

e) (2%) What is the computational intensity of the BLAS operation of C = C + A x B where A, B, and C are N x N matrices.

Multiplication: (2N-1) x N^2

Addition: N^2

Total: 2N^3

f) (2%) What is the name of the benchmark test to rank the list of top500 computers in the world.

HPL

g) (2%) Write down the Bayes’ theorem.

p(X|Y)p(Y)=P(Y|X)p(X)

h) (2%) What is the difference between regression and classification?

Regression gives a predicted value while classification gives a predicted class

i) (2%) Write down the formula for precision and recall, TP is true positive, TN is true negative, FP is false position, and FN is false negative.

Precision = TP / (TP + FP)

Recall = TP / (TP + FN)

j) Given the following parametric model, (2%) Is (w0) ^ 2 + w1 (x^2) + w2 (y^2), w3 (xy) + w4 (y) + w5 (x), where wi are the parameters, is it a linear parametric model (yes or No)?

No

# Question 2

a) (10%) A newly built supercomputer named, MA3330-BigIron, is composed of 1000000 units of CPU. Each CPU has 4 cores, 64GB RAM, and a clock speed of 2.5 GHz. Each core has 8 floating units (perform 8 DP operations in one clock cycle). What is the theoretical double precision peak performance of the MA3330-BigIron in PetaFLOPS?

Peak FLOPS = 1000000 CPU * 2.5 GHz * 8 operations * 4 cores = 80 PFLOPS

b) (10%) Given the memory of BigIron, what is the maximum dimension (N) of a single NxNmatrix A that BigIron can hold?

Memory = 64GB = N^2 * 8

Hence N = floor(sqrt(64e9 / 8)) = 89442

# Question 3

a) (5%) A(i, j, k) is a 3-dimensional matrix (tensor) of size (shape) 2 x 3 x 4. A is composed of 24 numbers ranging from 1 to 24. Print out the matrix A using numpy array?

In [ ]:
import numpy as np

A = np.arange(1, 25).reshape(2, 3, 4)
print(A)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


b) (5%) Based on A, print out the “j = 1” slice of A.

In [ ]:
print(A[:, 1, :])

[[ 5  6  7  8]
 [17 18 19 20]]


c) (5%) Based on A, print out the submatrix A where j=1 and k starts from 1 and ends at 3,that is (1:3)?

In [ ]:
print(A[:, 1, 1:3])

[[ 6  7]
 [18 19]]


d) (5%) Based on A, write out the new matrix B which collapses the “i” index to the “j” index.

In [ ]:
import tensorflow as tf

B = tf.reshape(A, [2*3, 4])
print(B)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]], shape=(6, 4), dtype=int64)


# Question 4

(5% for each sub-problem):

(a)

In [96]:
X = np.array([[1.6, 0.5], [2.1, -0.8], [3.4, 0.2], [3.9, -0.5], [4.3, 1.2], [5.2, 0.7], [6.1, 0.4], [7.4, -0.5]])
Y = np.array([3, 2.4, 4.7, 4.5, 6.6, 7.1, 7.3, 8.1])

x1 = X[:, 0]
x2 = X[:, 1]
sum_x1 = sum(x1)
sum_x2 = sum(x2)
sum_y = sum(Y)
sum_x1x1 = x1 @ x1.T
sum_x1x2 = x1 @ x2.T
sum_x1y = x1 @ Y.T
sum_x2x2 = x2 @ x2.T
sum_x2y = x2 @ Y.T
sum_yy = Y @ Y.T

Q = np.array([
  [1, sum_x1 / 8, sum_x2 / 8],
  [sum_x1 / 8, sum_x1x1 / 8, sum_x1x2 / 8],
  [sum_x2 / 8, sum_x1x2 / 8, sum_x2x2 / 8]
])
b = np.array([sum_y / 4, sum_x1y / 4, sum_x2y / 4])

print(Q)
print(b)

[[ 1.       4.25     0.15   ]
 [ 4.25    21.405    0.67375]
 [ 0.15     0.67375  0.44   ]]
[10.925  53.285   2.5075]


(b)

In [95]:
t = np.array([1, 2, 7])
d = [b - Q @ t]
g = -b

for i in range(8):
  t = t + -(g.T @ d[i]) / (d[i].T @ Q @ d[i])
  g = Q @ t - b
  d.append(-g + ((g.T @ Q @ d[i]) / (d[i].T @ Q @ d[i])) * d[i])

(c)

In [94]:
print(t)

[3.23833739 4.23833739 9.23833739]


(d) Use Scikit-learn package to find C0, C1, C2

In [ ]:
from sklearn.linear_model import LinearRegression

lr1 = LinearRegression()
lr1.fit(X, Y)

C0 = lr1.intercept_
C1 = lr1.coef_[0]
C2 = lr1.coef_[1]

print(C0)
print(C1)
print(C2)

1.0062655431341234
1.0149152447395702
0.9522977781513547


# Question 5

a) (5%) Import the data set ‘load_digits’ from ‘sklearn.datasets’. Check out the 'keys' of the data set.

In [ ]:
from sklearn.datasets import load_digits

print(load_digits().keys())

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])


b) (5%) Consider the problem of classifying an image of a hand-written digit as ‘a’ or ‘nota’, where ‘a’ is the last digit of your student ID number. Define a new array for the binary target values. Then split the data set into training and test data sets.

In [ ]:
from sklearn.model_selection import train_test_split

digit_a = 1

def is_digit_a(n):
  return 0 + (n == digit_a)

X = load_digits().data
Y = np.array(list(map(is_digit_a, load_digits().target)))
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

c) (5%) Construct a classifier by applying the method of logistic regression. You can apply the Scikit-learn package.

In [ ]:
from sklearn.linear_model import LogisticRegression

lr2 = LogisticRegression(solver='newton-cg', penalty='none')
lr2.fit(X_train, Y_train)

LogisticRegression(penalty='none', solver='newton-cg')

d) (5%) Compute the confusion matrices for the (i) training and (ii) test data, respectively. You can apply the Scikit-learn package.

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

C_train = confusion_matrix(Y_train, lr2.predict(X_train))
A_train = accuracy_score(Y_train, lr2.predict(X_train))
print(C_train)
print(A_train)

C_test = confusion_matrix(Y_test, lr2.predict(X_test))
A_test = accuracy_score(Y_test, lr2.predict(X_test))
print(C_test)
print(A_test)

[[1207    0]
 [   0  140]]
1.0
[[399   9]
 [  5  37]]
0.9688888888888889
